-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 12:39:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_graphome;
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_graphome;
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_graphome;` DEFAULT CHARACTER SET utf8 ;
USE `db_graphome;` ;

-- -----------------------------------------------------
-- Table `db_graphome;`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_graphome;`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_graphome;`.`tb_subtemas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_graphome;`.`tb_subtemas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `resumo_desc` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_graphome;`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_graphome;`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_graphome;`.`tb_Postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_graphome;`.`tb_Postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `textos` VARCHAR(1000) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `midia` VARCHAR(255) NULL,
  `data` DATE NOT NULL,
  `curtir` BIGINT NULL,
  `temas_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_Postagens_tb_temas_idx` (`temas_id` ASC) VISIBLE,
  INDEX `fk_tb_Postagens_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_Postagens_tb_temas`
    FOREIGN KEY (`temas_id`)
    REFERENCES `db_graphome;`.`tb_subtemas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_Postagens_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_graphome;`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
